export const NOTIFICATION_TYPE = {
    ERROR: 'ERROR',
    WARNING: 'WARNING',
    NORMAL: 'NORMAL',
};
export const ANON_TOKEN_COOKIE = 'TOKEN';
export const PRIVATE_TOKEN_COOKIE = 'PRIVATETOKEN';

export const CATEGORIES = [
    {
        name: 'TYPE',
        fields: [
            {
                id: 1,
                name: 'Painting',
                description: null,
                bitValue: 1,
                exampleImageUrl: null,
            },
            {
                id: 2,
                name: 'Drawing',
                description: null,
                bitValue: 2,
                exampleImageUrl: null,
            },
            {
                id: 3,
                name: 'Photography',
                description: null,
                bitValue: 4,
                exampleImageUrl: null,
            },
            {
                id: 4,
                name: 'Sculpture',
                description: null,
                bitValue: 8,
                exampleImageUrl: null,
            },
            {
                id: 5,
                name: '3D Object',
                description: null,
                bitValue: 16,
                exampleImageUrl: null,
            },
            {
                id: 6,
                name: 'Print/Multiple',
                description: null,
                bitValue: 32,
                exampleImageUrl: null,
            },
        ],
    },
    {
        name: 'CONTAINS_PEOPLE',
        fields: [
            {
                id: 1,
                name: 'Male',
                description: null,
                bitValue: 1,
                exampleImageUrl: null,
            },
            {
                id: 2,
                name: 'Female',
                description: null,
                bitValue: 2,
                exampleImageUrl: null,
            },
            {
                id: 3,
                name: 'Nudes',
                description: null,
                bitValue: 4,
                exampleImageUrl: null,
            },
            {
                id: 4,
                name: 'Faces',
                description: null,
                bitValue: 8,
                exampleImageUrl: null,
            },
            {
                id: 5,
                name: 'Groups',
                description: null,
                bitValue: 16,
                exampleImageUrl: null,
            },
            {
                id: 6,
                name: 'Portraiture',
                description: null,
                bitValue: 32,
                exampleImageUrl: null,
            },
            {
                id: 7,
                name: 'Children',
                description: null,
                bitValue: 64,
                exampleImageUrl: null,
            },
            {
                id: 8,
                name: 'Gender Fluid',
                description: null,
                bitValue: 128,
                exampleImageUrl: null,
            },
        ],
    },
    {
        name: 'PALETTE',
        fields: [
            {
                id: 1,
                name: 'Black & White',
                description: null,
                bitValue: 1,
                exampleImageUrl: null,
            },
            {
                id: 2,
                name: 'Light Tones',
                description: null,
                bitValue: 2,
                exampleImageUrl: null,
            },
            {
                id: 3,
                name: 'Dark Tones',
                description: null,
                bitValue: 4,
                exampleImageUrl: null,
            },
            {
                id: 4,
                name: 'Pastels',
                description: null,
                bitValue: 8,
                exampleImageUrl: null,
            },
            {
                id: 5,
                name: 'Vivid & Bright',
                description: null,
                bitValue: 16,
                exampleImageUrl: null,
            },
            {
                id: 6,
                name: 'Muted',
                description: null,
                bitValue: 32,
                exampleImageUrl: null,
            },
            {
                id: 7,
                name: 'Warm Tones',
                description: null,
                bitValue: 64,
                exampleImageUrl: null,
            },
            {
                id: 8,
                name: 'Cool Tones',
                description: null,
                bitValue: 128,
                exampleImageUrl: null,
            },
        ],
    },
    {
        name: 'CONTAINS_COLORS',
        fields: [
            {
                id: 1,
                name: 'Red',
                description: null,
                bitValue: 1,
                exampleImageUrl: null,
            },
            {
                id: 2,
                name: 'Orange',
                description: null,
                bitValue: 2,
                exampleImageUrl: null,
            },
            {
                id: 3,
                name: 'Yellow',
                description: null,
                bitValue: 4,
                exampleImageUrl: null,
            },
            {
                id: 4,
                name: 'Blue',
                description: null,
                bitValue: 8,
                exampleImageUrl: null,
            },
            {
                id: 5,
                name: 'Green',
                description: null,
                bitValue: 16,
                exampleImageUrl: null,
            },
            {
                id: 6,
                name: 'Purple',
                description: null,
                bitValue: 32,
                exampleImageUrl: null,
            },
            {
                id: 7,
                name: 'Pink',
                description: null,
                bitValue: 64,
                exampleImageUrl: null,
            },
            {
                id: 8,
                name: 'Brown',
                description: null,
                bitValue: 128,
                exampleImageUrl: null,
            },
            {
                id: 9,
                name: 'Black',
                description: null,
                bitValue: 256,
                exampleImageUrl: null,
            },
            {
                id: 10,
                name: 'White',
                description: null,
                bitValue: 512,
                exampleImageUrl: null,
            },
            {
                id: 11,
                name: 'Grey',
                description: null,
                bitValue: 1024,
                exampleImageUrl: null,
            },
            {
                id: 12,
                name: 'Cyan',
                description: null,
                bitValue: 2048,
                exampleImageUrl: null,
            },
            {
                id: 13,
                name: 'Gold',
                description: null,
                bitValue: 4096,
                exampleImageUrl: null,
            },
            {
                id: 14,
                name: 'Magenta',
                description: null,
                bitValue: 8192,
                exampleImageUrl: null,
            },
        ],
    },
    {
        name: 'MEDIUM',
        fields: [
            {
                id: 1,
                name: 'Oil',
                description: null,
                bitValue: 1,
                exampleImageUrl: null,
            },
            {
                id: 2,
                name: 'Acrylic',
                description: null,
                bitValue: 2,
                exampleImageUrl: null,
            },
            {
                id: 3,
                name: 'Watercolor',
                description: null,
                bitValue: 4,
                exampleImageUrl: null,
            },
            {
                id: 4,
                name: 'Wax',
                description: null,
                bitValue: 8,
                exampleImageUrl: null,
            },
            {
                id: 5,
                name: 'Charcoal',
                description: null,
                bitValue: 16,
                exampleImageUrl: null,
            },
            {
                id: 6,
                name: 'Pencil',
                description: null,
                bitValue: 32,
                exampleImageUrl: null,
            },
            {
                id: 7,
                name: 'Collage',
                description: null,
                bitValue: 64,
                exampleImageUrl: null,
            },
            {
                id: 8,
                name: 'Mixed Media',
                description: null,
                bitValue: 128,
                exampleImageUrl: null,
            },
            {
                id: 9,
                name: 'Metallic',
                description: null,
                bitValue: 256,
                exampleImageUrl: null,
            },
            {
                id: 10,
                name: 'Spray Paint',
                description: null,
                bitValue: 512,
                exampleImageUrl: null,
            },
            {
                id: 11,
                name: 'Wood',
                description: null,
                bitValue: 1024,
                exampleImageUrl: null,
            },
            {
                id: 12,
                name: 'Metal',
                description: null,
                bitValue: 2048,
                exampleImageUrl: null,
            },
            {
                id: 13,
                name: 'Clay',
                description: null,
                bitValue: 4096,
                exampleImageUrl: null,
            },
            {
                id: 14,
                name: 'Giclee',
                description: null,
                bitValue: 8192,
                exampleImageUrl: null,
            },
        ],
    },
    {
        name: 'SUBJECT',
        fields: [
            {
                id: 1,
                name: 'Abstract',
                description: null,
                bitValue: 1,
                exampleImageUrl: null,
            },
            {
                id: 2,
                name: 'Realism',
                description: null,
                bitValue: 2,
                exampleImageUrl: null,
            },
            {
                id: 3,
                name: 'Still Life',
                description: null,
                bitValue: 4,
                exampleImageUrl: null,
            },
            {
                id: 4,
                name: 'Geometric',
                description: null,
                bitValue: 8,
                exampleImageUrl: null,
            },
            {
                id: 5,
                name: 'Figurative',
                description: null,
                bitValue: 16,
                exampleImageUrl: null,
            },
            {
                id: 6,
                name: 'Landscape',
                description: null,
                bitValue: 32,
                exampleImageUrl: null,
            },
            {
                id: 7,
                name: 'Music/Dance',
                description: null,
                bitValue: 64,
                exampleImageUrl: null,
            },
            {
                id: 8,
                name: 'Marine/Nautical',
                description: null,
                bitValue: 128,
                exampleImageUrl: null,
            },
            {
                id: 9,
                name: 'Historical',
                description: null,
                bitValue: 256,
                exampleImageUrl: null,
            },
        ],
    },
    {
        name: 'SUBJECTIVE',
        fields: [
            {
                id: 1,
                name: 'Chaotic',
                description: null,
                bitValue: 1,
                exampleImageUrl: null,
            },
            {
                id: 2,
                name: 'Serene',
                description: null,
                bitValue: 2,
                exampleImageUrl: null,
            },
            {
                id: 3,
                name: 'Textured',
                description: null,
                bitValue: 4,
                exampleImageUrl: null,
            },
            {
                id: 4,
                name: 'Vibrant',
                description: null,
                bitValue: 8,
                exampleImageUrl: null,
            },
            {
                id: 5,
                name: 'Symmetrical',
                description: null,
                bitValue: 16,
                exampleImageUrl: null,
            },
            {
                id: 6,
                name: 'Muted',
                description: null,
                bitValue: 32,
                exampleImageUrl: null,
            },
        ],
    },
    {
        name: 'CONTAINS_PLACES',
        fields: [
            {
                id: 1,
                name: 'Landscape',
                description: null,
                bitValue: 1,
                exampleImageUrl: null,
            },
            {
                id: 2,
                name: 'Nature',
                description: null,
                bitValue: 2,
                exampleImageUrl: null,
            },
            {
                id: 3,
                name: 'Structural/Architectural',
                description: null,
                bitValue: 4,
                exampleImageUrl: null,
            },
            {
                id: 4,
                name: 'Forest',
                description: null,
                bitValue: 8,
                exampleImageUrl: null,
            },
            {
                id: 5,
                name: 'Ocean',
                description: null,
                bitValue: 16,
                exampleImageUrl: null,
            },
            {
                id: 6,
                name: 'Jungle',
                description: null,
                bitValue: 32,
                exampleImageUrl: null,
            },
            {
                id: 7,
                name: 'Desert',
                description: null,
                bitValue: 64,
                exampleImageUrl: null,
            },
            {
                id: 8,
                name: 'Flowers',
                description: null,
                bitValue: 128,
                exampleImageUrl: null,
            },
        ],
    },
    {
        name: 'CONTAINS_ANIMALS',
        fields: [
            {
                id: 1,
                name: 'Domesticated',
                description: null,
                bitValue: 1,
                exampleImageUrl: null,
            },
            {
                id: 2,
                name: 'Wild',
                description: null,
                bitValue: 2,
                exampleImageUrl: null,
            },
            {
                id: 3,
                name: 'Cats',
                description: null,
                bitValue: 4,
                exampleImageUrl: null,
            },
            {
                id: 4,
                name: 'Dogs',
                description: null,
                bitValue: 8,
                exampleImageUrl: null,
            },
            {
                id: 5,
                name: 'Horses',
                description: null,
                bitValue: 16,
                exampleImageUrl: null,
            },
            {
                id: 6,
                name: 'Birds',
                description: null,
                bitValue: 32,
                exampleImageUrl: null,
            },
            {
                id: 7,
                name: 'Sea Creatures',
                description: null,
                bitValue: 64,
                exampleImageUrl: null,
            },
            {
                id: 8,
                name: 'Insects',
                description: null,
                bitValue: 128,
                exampleImageUrl: null,
            },
        ],
    },
];
