const discoverForYouPlaceholder = [
    {
        art: {
            name: 'title',
            fullSizeImageUrl: './artCardPlaceholder.png',
            height: 24,
            width: 24,
            depth: 24,
            artId: 24,
        },
        price: 100,
    },
    {
        art: {
            name: 'title',
            fullSizeImageUrl: './artCardPlaceholder.png',
            height: 24,
            width: 24,
            depth: 24,
            artId: 24,
        },
        price: 100,
    },
    {
        art: {
            name: 'title',
            fullSizeImageUrl: './artCardPlaceholder.png',
            height: 24,
            width: 24,
            depth: 24,
            artId: 24,
        },
        price: 100,
    },
    {
        art: {
            name: 'title',
            fullSizeImageUrl: './artCardPlaceholder.png',
            height: 24,
            width: 24,
            depth: 24,
            artId: 24,
        },
        price: 100,
    },
    {
        art: {
            name: 'title',
            fullSizeImageUrl: './artCardPlaceholder.png',
            height: 24,
            width: 24,
            depth: 24,
            artId: 24,
        },
        price: 100,
    },
    {
        art: {
            name: 'title',
            fullSizeImageUrl: './artCardPlaceholder.png',
            height: 24,
            width: 24,
            depth: 24,
            artId: 24,
        },
        price: 100,
    },
];

const followingPlaceholder = [
    {
        id: 6,
        token: 'trager',
        galleryTypeId: 1,
        name: 'Trager Contemporary',
        description: '',
        primaryContactPhone: '',
        primaryContactEmail: '',
        primaryContactFirstName: '',
        primaryContactLastName: '',
        logoImageUrl: '',
        logoMediaType: '',
        descriptionImageUrl: '',
        descriptionImageMediaType: '',
        visibleInSearch: false,
        inventoryVisibleInSearch: false,
        donationUrl: '',
        numberForSale: 0,
        numberSold: 0,
        listings: [
            {
                price: 2000,
                art: {
                    sequenceId: 0,
                    artId: 33,
                    token: 'kellychelena-a1',
                    name: 'Liquid Sunshine',
                    description: '',
                    creationYear: 0,
                    registrationDate: '0001-01-01T00:00:00',
                    width: 36,
                    height: 24,
                    depth: 2,
                    weight: 0,
                    metricWidth: 0.9144,
                    metricHeight: 0.6096,
                    metricDepth: 0.0508,
                    pixelWidth: 0,
                    pixelHeight: 0,
                    mediaType: '',
                    fullSizeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.41.jpg',
                    thumbnailMediaType: '',
                    thumbnailImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.41t.jpg',
                    artModeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.41t1000.jpg',
                    typeBitMap: 0,
                    mediumBitMap: 0,
                    subjectBitMap: 0,
                    styleBitMap: 0,
                    colorBitMap: 0,
                    paletteBitMap: 0,
                    subjectiveThemeBitMap: 0,
                    contentPeopleBitMap: 0,
                    contentPlacesBitMap: 0,
                    contentAnimalsBitMap: 0,
                },
            },
            {
                price: 2000,
                art: {
                    sequenceId: 1,
                    artId: 37,
                    token: 'kellychelena-a5',
                    name: 'Lemon Ice',
                    description: '',
                    creationYear: 0,
                    registrationDate: '0001-01-01T00:00:00',
                    width: 36,
                    height: 24,
                    depth: 1,
                    weight: 0,
                    metricWidth: 0.9144,
                    metricHeight: 0.6096,
                    metricDepth: 0.0254,
                    pixelWidth: 0,
                    pixelHeight: 0,
                    mediaType: '',
                    fullSizeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.45.jpg',
                    thumbnailMediaType: '',
                    thumbnailImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.45t.jpg',
                    artModeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.45t1000.jpg',
                    typeBitMap: 0,
                    mediumBitMap: 0,
                    subjectBitMap: 0,
                    styleBitMap: 0,
                    colorBitMap: 0,
                    paletteBitMap: 0,
                    subjectiveThemeBitMap: 0,
                    contentPeopleBitMap: 0,
                    contentPlacesBitMap: 0,
                    contentAnimalsBitMap: 0,
                },
            },
            {
                price: 4200,
                art: {
                    sequenceId: 2,
                    artId: 38,
                    token: 'jondavenport-a1',
                    name: 'Audrey in Red and Blue',
                    description: '',
                    creationYear: 0,
                    registrationDate: '0001-01-01T00:00:00',
                    width: 48,
                    height: 36,
                    depth: 2,
                    weight: 0,
                    metricWidth: 1.2192,
                    metricHeight: 0.9144,
                    metricDepth: 0.0508,
                    pixelWidth: 0,
                    pixelHeight: 0,
                    mediaType: '',
                    fullSizeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.46.jpg',
                    thumbnailMediaType: '',
                    thumbnailImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.46t.jpg',
                    artModeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.46t1000.jpg',
                    typeBitMap: 0,
                    mediumBitMap: 0,
                    subjectBitMap: 0,
                    styleBitMap: 0,
                    colorBitMap: 0,
                    paletteBitMap: 0,
                    subjectiveThemeBitMap: 0,
                    contentPeopleBitMap: 0,
                    contentPlacesBitMap: 0,
                    contentAnimalsBitMap: 0,
                },
            },
            {
                price: 3000,
                art: {
                    sequenceId: 3,
                    artId: 41,
                    token: 'davidfrench-a2',
                    name: 'Indigo',
                    description: '',
                    creationYear: 0,
                    registrationDate: '0001-01-01T00:00:00',
                    width: 33,
                    height: 33,
                    depth: 2,
                    weight: 0,
                    metricWidth: 0.8382,
                    metricHeight: 0.8382,
                    metricDepth: 0.0508,
                    pixelWidth: 0,
                    pixelHeight: 0,
                    mediaType: '',
                    fullSizeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.50.jpg',
                    thumbnailMediaType: '',
                    thumbnailImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.50t.jpg',
                    artModeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.50t1000.jpg',
                    typeBitMap: 0,
                    mediumBitMap: 0,
                    subjectBitMap: 0,
                    styleBitMap: 0,
                    colorBitMap: 0,
                    paletteBitMap: 0,
                    subjectiveThemeBitMap: 0,
                    contentPeopleBitMap: 0,
                    contentPlacesBitMap: 0,
                    contentAnimalsBitMap: 0,
                },
            },
            {
                price: 3000,
                art: {
                    sequenceId: 4,
                    artId: 43,
                    token: 'davidfrench-a4',
                    name: 'Untitled (cobalt turquoise)',
                    description: '',
                    creationYear: 0,
                    registrationDate: '0001-01-01T00:00:00',
                    width: 33,
                    height: 33,
                    depth: 2,
                    weight: 0,
                    metricWidth: 0.8382,
                    metricHeight: 0.8382,
                    metricDepth: 0.0508,
                    pixelWidth: 0,
                    pixelHeight: 0,
                    mediaType: '',
                    fullSizeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.52.jpg',
                    thumbnailMediaType: '',
                    thumbnailImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.52t.jpg',
                    artModeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.52t1000.jpg',
                    typeBitMap: 0,
                    mediumBitMap: 0,
                    subjectBitMap: 0,
                    styleBitMap: 0,
                    colorBitMap: 0,
                    paletteBitMap: 0,
                    subjectiveThemeBitMap: 0,
                    contentPeopleBitMap: 0,
                    contentPlacesBitMap: 0,
                    contentAnimalsBitMap: 0,
                },
            },
            {
                price: 2500,
                art: {
                    sequenceId: 5,
                    artId: 44,
                    token: 'tonygill-a1',
                    name: 'Waccamaw Neck',
                    description: 'boat',
                    creationYear: 0,
                    registrationDate: '0001-01-01T00:00:00',
                    width: 40,
                    height: 30,
                    depth: 1,
                    weight: 0,
                    metricWidth: 1.016,
                    metricHeight: 0.762,
                    metricDepth: 0.0254,
                    pixelWidth: 0,
                    pixelHeight: 0,
                    mediaType: '',
                    fullSizeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.53.jpg',
                    thumbnailMediaType: '',
                    thumbnailImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.53t.jpg',
                    artModeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.53t1000.jpg',
                    typeBitMap: 0,
                    mediumBitMap: 0,
                    subjectBitMap: 0,
                    styleBitMap: 0,
                    colorBitMap: 0,
                    paletteBitMap: 0,
                    subjectiveThemeBitMap: 0,
                    contentPeopleBitMap: 0,
                    contentPlacesBitMap: 0,
                    contentAnimalsBitMap: 0,
                },
            },
            {
                price: 3000,
                art: {
                    sequenceId: 6,
                    artId: 45,
                    token: 'tonygill-a2',
                    name: 'Waccamaw Neck (framed)',
                    description: 'boat ',
                    creationYear: 0,
                    registrationDate: '0001-01-01T00:00:00',
                    width: 41,
                    height: 31,
                    depth: 1,
                    weight: 0,
                    metricWidth: 1.0414,
                    metricHeight: 0.7874,
                    metricDepth: 0.0254,
                    pixelWidth: 0,
                    pixelHeight: 0,
                    mediaType: '',
                    fullSizeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.54.jpg',
                    thumbnailMediaType: '',
                    thumbnailImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.54t.jpg',
                    artModeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.54t1000.jpg',
                    typeBitMap: 0,
                    mediumBitMap: 0,
                    subjectBitMap: 0,
                    styleBitMap: 0,
                    colorBitMap: 0,
                    paletteBitMap: 0,
                    subjectiveThemeBitMap: 0,
                    contentPeopleBitMap: 0,
                    contentPlacesBitMap: 0,
                    contentAnimalsBitMap: 0,
                },
            },
            {
                price: 2500,
                art: {
                    sequenceId: 7,
                    artId: 46,
                    token: 'tonygill-a3',
                    name: 'Murrells inlet',
                    description: 'boat',
                    creationYear: 0,
                    registrationDate: '0001-01-01T00:00:00',
                    width: 40,
                    height: 30,
                    depth: 1,
                    weight: 0,
                    metricWidth: 1.016,
                    metricHeight: 0.762,
                    metricDepth: 0.0254,
                    pixelWidth: 0,
                    pixelHeight: 0,
                    mediaType: '',
                    fullSizeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.55.jpg',
                    thumbnailMediaType: '',
                    thumbnailImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.55t.jpg',
                    artModeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.55t1000.jpg',
                    typeBitMap: 0,
                    mediumBitMap: 0,
                    subjectBitMap: 0,
                    styleBitMap: 0,
                    colorBitMap: 0,
                    paletteBitMap: 0,
                    subjectiveThemeBitMap: 0,
                    contentPeopleBitMap: 0,
                    contentPlacesBitMap: 0,
                    contentAnimalsBitMap: 0,
                },
            },
            {
                price: 2500,
                art: {
                    sequenceId: 8,
                    artId: 47,
                    token: 'tonygill-a4',
                    name: 'Quemby Creek',
                    description: '',
                    creationYear: 0,
                    registrationDate: '0001-01-01T00:00:00',
                    width: 30,
                    height: 48,
                    depth: 1,
                    weight: 0,
                    metricWidth: 0.762,
                    metricHeight: 1.2192,
                    metricDepth: 0.0254,
                    pixelWidth: 0,
                    pixelHeight: 0,
                    mediaType: '',
                    fullSizeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.56.jpg',
                    thumbnailMediaType: '',
                    thumbnailImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.56t.jpg',
                    artModeImageUrl: 'https://artarticulator.blob.core.windows.net/partner-images/7.56t1000.jpg',
                    typeBitMap: 0,
                    mediumBitMap: 0,
                    subjectBitMap: 0,
                    styleBitMap: 0,
                    colorBitMap: 0,
                    paletteBitMap: 0,
                    subjectiveThemeBitMap: 0,
                    contentPeopleBitMap: 0,
                    contentPlacesBitMap: 0,
                    contentAnimalsBitMap: 0,
                },
            },
        ],
    },
];

const useDiscover = () => {
    return {
        discoverForYouPlaceholder,
        followingPlaceholder,
    };
};

export default useDiscover;
